-- Chapter 04. 기본 CRUD 통합 참고 파일
-- 새로 학습하는 독자는 번호 파일을 순서대로 사용하세요.
--   01_create_students.sql
--   02_insert_students.sql
--   03_select_students.sql
--   04_update_delete_students.sql
--
-- 이 파일은 기존 링크와 사용자를 위한 통합 참고 자료입니다.
-- 번호 SQL 파일에 있는 시작 상태·권한 검사는 가독성을 위해 일부 생략되어 있습니다.
-- 파일 전체를 한꺼번에 실행하지 말고 필요한 구간만 선택합니다.
-- 자동 커밋 상태에서는 변경 SQL이 실행 직후 확정될 수 있습니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- ============================================================
SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- 1. 테이블 생성: 테이블이 없을 때 한 번만 실행
-- ============================================================
CREATE TABLE public.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    major VARCHAR(100),
    grade INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. 데이터 입력: 빈 테이블에서 한 번만 실행
-- ============================================================
INSERT INTO public.students (name, email, major, grade)
VALUES ('김민지', 'minji@example.com', '컴퓨터공학', 2)
RETURNING id, name, created_at;

INSERT INTO public.students (name, email, major, grade)
VALUES
    ('이준호', 'junho@example.com', '데이터사이언스', 3),
    ('박서연', 'seoyeon@example.com', '경영학', 1),
    ('최현우', 'hyunwoo@example.com', '컴퓨터공학', 4),
    ('정하늘', 'haneul@example.com', 'AI데이터공학', 2);

INSERT INTO public.students (name, email)
VALUES ('윤서진', 'seojin@example.com');

SELECT COUNT(*) AS student_count
FROM public.students;

-- ============================================================
-- 3. 기본 SELECT와 WHERE
-- ============================================================
SELECT id, name, email, major, grade
FROM public.students
ORDER BY id ASC;

SELECT id, name, major
FROM public.students
WHERE major = '컴퓨터공학'
ORDER BY id ASC;

SELECT id, name, grade
FROM public.students
WHERE grade >= 3
ORDER BY grade DESC, id ASC;

SELECT id, name, major
FROM public.students
WHERE major IN ('컴퓨터공학', '데이터사이언스')
ORDER BY id ASC;

SELECT id, name
FROM public.students
WHERE name LIKE '김%'
ORDER BY id ASC;

-- ============================================================
-- 4. NULL과 중복 제거
-- ============================================================
SELECT id, name, major, grade
FROM public.students
WHERE major IS NULL
ORDER BY id ASC;

SELECT id, name, major
FROM public.students
WHERE major <> '경영학'
   OR major IS NULL
ORDER BY id ASC;

SELECT DISTINCT major
FROM public.students
WHERE major IS NOT NULL
ORDER BY major ASC;

-- ============================================================
-- 5. 정렬과 LIMIT
-- ============================================================
SELECT id, name, grade
FROM public.students
ORDER BY grade ASC, id ASC;

SELECT id, name, created_at
FROM public.students
ORDER BY created_at DESC, id DESC
LIMIT 3;

-- ============================================================
-- 6. 선택 학습: PostgreSQL 문법
-- ============================================================
SELECT id, name, email
FROM public.students
WHERE email ILIKE '%EXAMPLE.COM'
ORDER BY id ASC;

SELECT id, name, grade
FROM public.students
ORDER BY grade DESC NULLS LAST, id ASC;

SELECT id, name, major
FROM public.students
WHERE major IS DISTINCT FROM '경영학'
ORDER BY id ASC;

SELECT CAST('3' AS INTEGER) AS cast_result;
SELECT '3'::INTEGER AS shorthand_result;

-- ============================================================
-- 7. UPDATE: 아래 세 문장을 순서대로 선택 실행
-- ============================================================
SELECT id, name, email, grade
FROM public.students
WHERE email = 'junho@example.com';

UPDATE public.students
SET grade = 4
WHERE email = 'junho@example.com'
RETURNING id, name, grade;

SELECT id, name, email, grade
FROM public.students
WHERE email = 'junho@example.com';

-- ============================================================
-- 8. DELETE: 아래 세 문장을 순서대로 선택 실행
-- ============================================================
SELECT id, name, email, major
FROM public.students
WHERE email = 'seoyeon@example.com';

DELETE FROM public.students
WHERE email = 'seoyeon@example.com'
RETURNING id, name, email;

SELECT id, name, email
FROM public.students
WHERE email = 'seoyeon@example.com';

-- ============================================================
-- 9. 실행하지 않는 위험 SQL 예시
-- ============================================================
-- UPDATE public.students SET grade = 1;
-- DELETE FROM public.students;
-- SELECT * FROM public.students WHERE major = NULL;
