-- Chapter 13. 요구사항을 기준으로 보완한 좋은 설계
-- 실행 전 01→02 파일을 순서대로 실행합니다.
-- Chapter 07에서 확정한 활성 신청 정책과 recorded_amount 의미를 유지합니다.
-- payments는 course_project에 추가되는 테이블이 아니라 ai_review_lab의 격리 리뷰 시나리오입니다.

SELECT current_database();
SELECT current_schema();
SHOW search_path;
SHOW transaction_read_only;

-- ============================================================
-- P13-V03. 생성 전 상태 확인
-- ============================================================
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다.',
            current_database();
    END IF;

    IF current_setting('transaction_read_only') = 'on' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 연결은 읽기 전용입니다.';
    END IF;

    IF to_regclass('ai_review_lab.bad_enrollments') IS NULL
       OR (SELECT COUNT(*) FROM ai_review_lab.bad_enrollments) <> 3 THEN
        RAISE EXCEPTION
            '실행 중단: 나쁜 설계 기준 데이터 3행이 준비되지 않았습니다.';
    END IF;

    IF to_regclass('ai_review_lab.students') IS NOT NULL
       OR to_regclass('ai_review_lab.instructors') IS NOT NULL
       OR to_regclass('ai_review_lab.courses') IS NOT NULL
       OR to_regclass('ai_review_lab.enrollments') IS NOT NULL
       OR to_regclass('ai_review_lab.payments') IS NOT NULL THEN
        RAISE EXCEPTION
            '실행 중단: 좋은 설계 테이블이 이미 존재합니다.';
    END IF;
END
$$;

BEGIN;

-- P13-R01: 학생 이메일은 공백이 아니며 정확히 같은 문자열이 중복될 수 없습니다.
-- 이메일 대소문자 정규화는 P13-D07에서 별도 결정합니다.
CREATE TABLE ai_review_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT uq_ai_review_students_email
        UNIQUE (email),

    CONSTRAINT chk_ai_review_students_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_ai_review_students_email_not_blank
        CHECK (char_length(trim(email)) > 0)
);

-- P13-R02: 강사 이메일은 공백이 아니며 정확히 같은 문자열이 중복될 수 없습니다.
CREATE TABLE ai_review_lab.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,

    CONSTRAINT uq_ai_review_instructors_email
        UNIQUE (email),

    CONSTRAINT chk_ai_review_instructors_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_ai_review_instructors_email_not_blank
        CHECK (char_length(trim(email)) > 0),

    CONSTRAINT chk_ai_review_instructors_specialty_not_blank
        CHECK (char_length(trim(specialty)) > 0)
);

-- P13-R03: 강의는 강사 한 명을 참조합니다.
CREATE TABLE ai_review_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    course_code VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL,
    price NUMERIC(12,0) NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_ai_review_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES ai_review_lab.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_ai_review_courses_code
        UNIQUE (course_code),

    CONSTRAINT chk_ai_review_courses_code_not_blank
        CHECK (char_length(trim(course_code)) > 0),

    CONSTRAINT chk_ai_review_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_ai_review_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_ai_review_courses_price
        CHECK (price >= 0)
);

-- P13-R04~R06: N:M 해소, 상태 허용값, 신청 시점 기록 금액 0 이상
-- Chapter 07·08과 같은 이름·타입·의미를 사용해 시점별 금액을 연결합니다.
CREATE TABLE ai_review_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    recorded_amount NUMERIC(12,0) NOT NULL,
    enrolled_at DATE NOT NULL,

    CONSTRAINT fk_ai_review_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES ai_review_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ai_review_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES ai_review_lab.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_ai_review_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_ai_review_enrollments_amount
        CHECK (recorded_amount >= 0)
);

-- P13-R09: Chapter 07에서 확정한 활성 신청 정책을 유지합니다.
-- 신청·수강중은 학생·강의 조합당 한 건이며 완료·취소 이력 뒤 재신청은 허용합니다.
CREATE UNIQUE INDEX uq_ai_review_enrollments_active
ON ai_review_lab.enrollments (student_id, course_id)
WHERE status IN ('신청', '수강중');

-- P13-R07~R08: 격리 리뷰 시나리오에서 결제는 신청을 참조합니다.
-- 카드번호·CVV 자체 대신 외부 결제 시스템 참조값 형태만 저장합니다.
-- 실제 시스템의 payment_reference도 조직의 보안·보관 정책에 따라 보호 대상이 될 수 있습니다.
-- P13-D02: 한 신청의 현재 결제 상태 한 건만 보존하는 단순 모델입니다.
-- P13-D06: 환불 샘플은 전액 환불이며 부분 환불 원장은 범위 밖입니다.
CREATE TABLE ai_review_lab.payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    amount NUMERIC(12,0) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    paid_at TIMESTAMPTZ,
    refunded_at TIMESTAMPTZ,
    payment_reference VARCHAR(100) NOT NULL,

    CONSTRAINT fk_ai_review_payments_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES ai_review_lab.enrollments(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_ai_review_payments_enrollment
        UNIQUE (enrollment_id),

    CONSTRAINT uq_ai_review_payments_reference
        UNIQUE (payment_reference),

    CONSTRAINT chk_ai_review_payments_reference_not_blank
        CHECK (char_length(trim(payment_reference)) > 0),

    CONSTRAINT chk_ai_review_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_ai_review_payments_status
        CHECK (
            payment_status IN (
                '결제대기',
                '결제완료',
                '결제실패',
                '환불'
            )
        ),

    -- 허용되지 않은 상태값은 위 status CHECK가 전담합니다.
    -- 이 CHECK는 유효한 상태일 때만 시각 조합을 판정해 반례 원인을 명확히 합니다.
    CONSTRAINT chk_ai_review_payments_timestamps
        CHECK (
            payment_status NOT IN (
                '결제대기',
                '결제완료',
                '결제실패',
                '환불'
            )
            OR
            (
                payment_status IN ('결제대기', '결제실패')
                AND paid_at IS NULL
                AND refunded_at IS NULL
            )
            OR
            (
                payment_status = '결제완료'
                AND paid_at IS NOT NULL
                AND refunded_at IS NULL
            )
            OR
            (
                payment_status = '환불'
                AND paid_at IS NOT NULL
                AND refunded_at IS NOT NULL
                AND refunded_at >= paid_at
            )
        )
);

-- COMMIT 전에 실제 생성 구조를 판정합니다.
DO $$
DECLARE
    actual_tables TEXT[];
    good_constraint_count INTEGER;
    good_identity_count INTEGER;
    money_type_count INTEGER;
    active_index_definition TEXT;
BEGIN
    SELECT array_agg(table_name ORDER BY table_name)
    INTO actual_tables
    FROM information_schema.tables
    WHERE table_schema = 'ai_review_lab';

    IF actual_tables IS DISTINCT FROM ARRAY[
        'bad_enrollments', 'courses', 'enrollments',
        'instructors', 'payments', 'students'
    ]::TEXT[] THEN
        RAISE EXCEPTION
            '좋은 구조 생성 중단: 정확한 테이블 집합이 아닙니다. 실제=%',
            actual_tables;
    END IF;

    SELECT COUNT(*)
    INTO good_constraint_count
    FROM pg_constraint
    WHERE connamespace = 'ai_review_lab'::regnamespace
      AND conrelid IN (
          'ai_review_lab.students'::regclass,
          'ai_review_lab.instructors'::regclass,
          'ai_review_lab.courses'::regclass,
          'ai_review_lab.enrollments'::regclass,
          'ai_review_lab.payments'::regclass
      );

    SELECT COUNT(*)
    INTO good_identity_count
    FROM information_schema.columns
    WHERE table_schema = 'ai_review_lab'
      AND table_name IN ('students','instructors','courses','enrollments','payments')
      AND column_name = 'id'
      AND is_identity = 'YES';

    SELECT COUNT(*)
    INTO money_type_count
    FROM information_schema.columns
    WHERE table_schema = 'ai_review_lab'
      AND (
          (table_name = 'courses' AND column_name = 'price')
          OR (table_name = 'enrollments' AND column_name = 'recorded_amount')
          OR (table_name = 'payments' AND column_name = 'amount')
      )
      AND data_type = 'numeric'
      AND numeric_precision = 12
      AND numeric_scale = 0;

    SELECT pg_get_indexdef('ai_review_lab.uq_ai_review_enrollments_active'::regclass)
    INTO active_index_definition;

    IF good_constraint_count <> 29
       OR good_identity_count <> 5
       OR money_type_count <> 3
       OR active_index_definition NOT LIKE '%WHERE ((status)::text = ANY%'
       OR active_index_definition NOT LIKE '%student_id, course_id%' THEN
        RAISE EXCEPTION
            '좋은 구조 생성 중단: constraints %, identity %, money %, active index %',
            good_constraint_count,
            good_identity_count,
            money_type_count,
            active_index_definition;
    END IF;
END
$$;

COMMIT;

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'ai_review_lab'
ORDER BY table_name;

SELECT
    schemaname,
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'ai_review_lab'
ORDER BY tablename, indexname;

DO $$
BEGIN
    RAISE NOTICE 'Chapter 13 good design schema creation passed';
END
$$;
